name : test
on : push
jobs: 
      test:
         runs-on: ubuntu-latest
         steps  : 
            - name : Get code
              uses : actions/checkout@v7
            - name : Install Ptyhon
              uses : actions/setup-python@v6 
              with :
                   python-version : '3.11'
            - name : intall the requirement packages
              run  : pip install -r requirement.txt 
            - name : test data quaality
              run  : pytest tests\test_data_quality.py 
