name : hands-on-lab
on :  workflow_dispatch
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name : print hellow world
            - run  : echo 'Hellow World !'
            - name : print Done
            - run  : echo "Done" 
    