name: test_workflow_job
on:
  workflow_call:
    inputs:
      python_version:
        type: string
        description: "python"
        default: '3.9'
        required: true
      test_case:
        type: string
jobs:
  test_reusable:
    runs-on: ubuntu-latest
    steps:
      - name: get code 
        uses: actions/checkout@v7
      - name: insatall python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: cacheing step
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: req-$${{hashFiles('requirements.txt')}}
      - name: setup requirements
        run: pip install -r requirements.txt
      - name: run test data quality
        run: pytest tests/test_data_quality.py